//! Creation of lattices (text/331): from generators, from a basis, from a
//! Gram matrix, and the standard, coordinate and scaled lattices.

use std::rc::Rc;

use calyx_flint::gr::{Ctx, Elem, Truth};
use calyx_flint::mat::Mat;
use calyx_flint::{Integer, Rational, lll_l2};

use super::{coordinate_lattice, lat, new, num_den, to_q};
use crate::error::{RResult, RuntimeError};
use crate::interp::{CallArgs, Interp};
use crate::intrinsics::matrices::{Mtrx, parent_info, set_entry};
use crate::intrinsics::one;
use crate::value::*;

/// Whether a symmetric matrix over Z or Q is positive definite: whether
/// its leading principal minors, which fraction-free elimination finds
/// as its pivots, are all positive.
pub fn positive_definite(m: &Mat) -> bool {
    let n = m.nrows();
    let (num, _) = num_den(m);
    let mut a: Vec<Vec<Integer>> = (0..n).map(|i| (0..n).map(|j| num.integer(i, j)).collect()).collect();
    let mut prev = Integer::one();
    for k in 0..n {
        if a[k][k].sign() <= 0 {
            return false;
        }
        for i in k + 1..n {
            for j in k + 1..n {
                a[i][j] = (&(&a[k][k] * &a[i][j]) - &(&a[i][k] * &a[k][j])).divexact(&prev);
            }
        }
        prev = a[k][k].clone();
    }
    true
}

/// The integer rows of a matrix over Z.
fn int_rows(m: &Mat) -> Vec<Vec<Integer>> {
    (0..m.nrows()).map(|i| (0..m.ncols()).map(|j| m.integer(i, j)).collect()).collect()
}

/// A basis of the lattice generated by the rows of `x`, reduced as
/// Magma's `Lattice` reduces it: by LLL with δ = 0.75 and η = 0.501 with
/// respect to the standard inner product (whatever the inner product
/// matrix `ip`), without the zero rows, with the first nonzero entry of
/// each row positive, and sorted by (Euclidean) norm, then in descending
/// lexicographic order.
fn reduced(x: &Mat) -> Mat {
    let n = x.ncols();
    let (xn, d) = num_den(x);
    let mut r = int_rows(&xn);
    lll_l2(&mut r, 0.75, 0.501);
    let mut rows: Vec<Vec<Rational>> = r.iter().map(|v| v.iter().map(|c| Rational::new(c, &d).expect("a nonzero denominator")).collect()).collect();
    rows.retain(|v| v.iter().any(|c| !c.is_zero()));
    for v in rows.iter_mut() {
        if v.iter().find(|c| !c.is_zero()).is_some_and(|c| c.sign() < 0) {
            for c in v.iter_mut() {
                *c = -&*c;
            }
        }
    }
    let norm = |v: &[Rational]| v.iter().fold(Rational::zero(), |s, c| &s + &(c * c));
    let mut keyed: Vec<(Rational, Vec<Rational>)> = rows.into_iter().map(|v| (norm(&v), v)).collect();
    keyed.sort_by(|(na, a), (nb, b)| na.cmp(nb).then_with(|| b.cmp(a)));
    let mut m = Mat::zero(&Ctx::rationals(), keyed.len(), n);
    for (i, (_, v)) in keyed.iter().enumerate() {
        for (j, c) in v.iter().enumerate() {
            m.set_rational(i, j, c).expect("a rational");
        }
    }
    m
}

/// The lattice generated by the rows of `x` with the inner product matrix
/// `ip` (both over Q), with a reduced basis.
pub(super) fn generated(x: &Mat, ip: &Mat) -> Rc<Struct> {
    new(&reduced(x), ip)
}

// ----- arguments --------------------------------------------------------------------------------

fn unsupported() -> RuntimeError {
    RuntimeError::runtime("Lattices over this ring are not supported")
}

/// A matrix over Z or Q, over Q, and its ring.
fn over_q(m: &Mtrx) -> RResult<(Mat, Value)> {
    let ring = m.ring().clone();
    if !ring.is_integers() && !ring.is_rationals() {
        return Err(unsupported());
    }
    Ok((to_q(&m.m), ring))
}

/// The entries of a sequence as an r by n matrix over Q, and the ring of
/// the sequence.
fn seq_matrix(it: &mut Interp, s: &SeqEnum, r: usize, n: usize) -> RResult<(Mat, Value)> {
    let ring = match &s.universe {
        None => Value::integers(),
        Some(u) if u.is_integers() || u.is_rationals() => u.clone(),
        Some(_) => return Err(unsupported()),
    };
    let q = Value::rationals();
    let mut m = Mat::zero(&Ctx::rationals(), r, n);
    for (k, x) in s.elems.iter().enumerate() {
        if !set_entry(it, &q, &mut m, k / n, k % n, x)? {
            return Err(unsupported());
        }
    }
    Ok((m, ring))
}

/// The rows given to `Lattice` or `LatticeWithBasis`: a matrix, a degree
/// with a sequence of entries, or an R-space (its basis). They come over Q,
/// with the ring they were given over and the number of arguments taken.
fn rows_arg(it: &mut Interp, a: &CallArgs) -> RResult<(Mat, Value, usize)> {
    match &a.args[0] {
        Value::Mat(m) => {
            let (x, ring) = over_q(m)?;
            Ok((x, ring, 1))
        }
        Value::Int(_) => {
            let n = a.usize(0)?;
            let s = a.seq(1)?;
            if n == 0 || s.elems.len() % n != 0 {
                return Err(RuntimeError::runtime(format!("Argument 2 does not have length a multiple of {n}")));
            }
            let (x, ring) = seq_matrix(it, s, s.elems.len() / n, n)?;
            Ok((x, ring, 2))
        }
        v => {
            let p = parent_info(v).expect("an R-space");
            let ring = p.ring.clone();
            if !ring.is_integers() && !ring.is_rationals() {
                return Err(unsupported());
            }
            let x = match &p.sub {
                Some(s) => to_q(&s.basis),
                None => Mat::identity(&Ctx::rationals(), p.ncols)?,
            };
            Ok((x, ring, 1))
        }
    }
}

/// Checks an inner product matrix (over Q): symmetric, and positive
/// definite unless the check is off.
fn check_form(m: &Mat, check_positive: bool) -> RResult<()> {
    if m.transpose().equal(m) != Truth::True {
        return Err(RuntimeError::runtime("Inner product matrix argument is not symmetric"));
    }
    if check_positive && !positive_definite(m) {
        return Err(RuntimeError::runtime("Inner product matrix argument is not positive definite"));
    }
    Ok(())
}

/// The inner product matrix given as argument k, if there is one (over the
/// ring of the rows), else the identity, over Q.
fn ip_arg(a: &CallArgs, k: usize, n: usize, ring: &Value) -> RResult<Mat> {
    let Some(Value::Mat(m)) = a.args.get(k) else { return Ok(Mat::identity(&Ctx::rationals(), n)?) };
    let (ip, r) = over_q(m)?;
    if r != *ring {
        return Err(RuntimeError::runtime("Arguments have incompatible coefficient rings"));
    }
    if ip.nrows() != n {
        return Err(RuntimeError::runtime(format!("Argument {} does not have {n} rows", k + 1)));
    }
    check_form(&ip, a.param_bool("CheckPositive")?)?;
    Ok(ip)
}

// ----- intrinsics -------------------------------------------------------------------------------

/// `Lattice(X)`, `Lattice(X, M)` and the like: the lattice generated by
/// the rows, with a reduced basis.
fn lattice(it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let (x, ring, k) = rows_arg(it, a)?;
    let ip = ip_arg(a, k, x.ncols(), &ring)?;
    one(Value::Struct(generated(&x, &ip)))
}

/// `LatticeWithBasis(B)` and the like: the lattice with the rows as its
/// basis.
fn lattice_with_basis(it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let (b, ring, k) = rows_arg(it, a)?;
    let ip = ip_arg(a, k, b.ncols(), &ring)?;
    if a.param_bool("CheckIndependent")? && b.rank()? != b.nrows() {
        return Err(RuntimeError::runtime("Basis matrix argument does not describe a basis"));
    }
    one(Value::Struct(new(&b, &ip)))
}

/// `LatticeWithGram(F)` and `LatticeWithGram(n, Q)`: the standard basis
/// with the inner product matrix F, given in full or by its lower
/// triangle.
fn lattice_with_gram(it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let f = match &a.args[0] {
        Value::Mat(m) => over_q(m)?.0,
        _ => {
            let n = a.usize(0)?;
            let s = a.seq(1)?;
            let len = s.elems.len();
            if len == n * n {
                seq_matrix(it, s, n, n)?.0
            } else if len == n * (n + 1) / 2 {
                let (t, _) = seq_matrix(it, s, 1, len)?;
                let mut f = Mat::zero(&Ctx::rationals(), n, n);
                let mut k = 0;
                for i in 0..n {
                    for j in 0..=i {
                        let x = t.entry(0, k);
                        f.set_entry(i, j, &x);
                        f.set_entry(j, i, &x);
                        k += 1;
                    }
                }
                f
            } else {
                return Err(RuntimeError::runtime(format!("Argument 2 should have length {} or {}", n * n, n * (n + 1) / 2)));
            }
        }
    };
    check_form(&f, a.param_bool("CheckPositive")?)?;
    one(Value::Struct(new(&Mat::identity(&Ctx::rationals(), f.nrows())?, &f)))
}

fn standard_lattice(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let n = a.usize(0)?;
    let e = Mat::identity(&Ctx::rationals(), n)?;
    one(Value::Struct(new(&e, &e)))
}

fn lattice_arg(a: &CallArgs, i: usize) -> Rc<Struct> {
    match &a.args[i] {
        Value::Struct(st) => st.clone(),
        _ => unreachable!("a lattice"),
    }
}

fn coordinate_lattice_of(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    one(Value::Struct(coordinate_lattice(&lattice_arg(a, 0))))
}

fn itself(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    one(a.args[0].clone())
}

/// `ScaledLattice(L, s)`: the coordinate lattice of L with its Gram matrix
/// scaled by s.
fn scaled_lattice(_it: &mut Interp, a: &mut CallArgs) -> RResult<Vals> {
    let st = lattice_arg(a, 0);
    let l = lat(&st);
    let s = match &a.args[1] {
        Value::Int(n) => Rational::from_integer(n),
        Value::Rat(q) => (**q).clone(),
        _ => unreachable!("an integer or rational"),
    };
    if s.sign() <= 0 {
        return Err(crate::intrinsics::bare(RuntimeError::runtime("Argument 2 must be positive.")));
    }
    let f = to_q(l.gram()).mul_scalar(&Elem::from_rational(&Ctx::rationals(), &s)?)?;
    one(Value::Struct(new(&Mat::identity(&Ctx::rationals(), l.rank())?, &f)))
}

pub fn register(it: &mut Interp) {
    let cp = [("CheckPositive", Value::Bool(true))];
    let ci = [("CheckIndependent", Value::Bool(true))];
    let both = [("CheckIndependent", Value::Bool(true)), ("CheckPositive", Value::Bool(true))];
    let doc = "The lattice generated by the rows of X (reduced by LLL), with the inner product matrix M.";
    it.def_params("Lattice", "X::Mtrx, M::AlgMatElt -> Lat", &cp, doc, lattice);
    it.def_params("Lattice", "n::RngIntElt, Q::SeqEnum, M::AlgMatElt -> Lat", &cp, doc, lattice);
    it.def_params("Lattice", "S::ModTupRng, M::AlgMatElt -> Lat", &cp, doc, lattice);
    let doc = "The lattice generated by the rows of X (reduced by LLL), with the standard inner product.";
    it.def("Lattice", "X::Mtrx -> Lat", doc, lattice);
    it.def("Lattice", "n::RngIntElt, Q::SeqEnum -> Lat", doc, lattice);
    it.def("Lattice", "S::ModTupRng -> Lat", doc, lattice);
    let doc = "The lattice with the rows of B as its basis, with the inner product matrix M.";
    it.def_params("LatticeWithBasis", "B::Mtrx, M::AlgMatElt -> Lat", &both, doc, lattice_with_basis);
    it.def_params("LatticeWithBasis", "n::RngIntElt, Q::SeqEnum, M::AlgMatElt -> Lat", &both, doc, lattice_with_basis);
    it.def_params("LatticeWithBasis", "S::ModTupRng, M::AlgMatElt -> Lat", &both, doc, lattice_with_basis);
    let doc = "The lattice with the rows of B as its basis, with the standard inner product.";
    it.def_params("LatticeWithBasis", "B::Mtrx -> Lat", &ci, doc, lattice_with_basis);
    it.def_params("LatticeWithBasis", "n::RngIntElt, Q::SeqEnum -> Lat", &ci, doc, lattice_with_basis);
    it.def_params("LatticeWithBasis", "S::ModTupRng -> Lat", &ci, doc, lattice_with_basis);
    let doc = "The lattice with the standard basis and the Gram matrix F.";
    it.def_params("LatticeWithGram", "F::AlgMatElt -> Lat", &cp, doc, lattice_with_gram);
    it.def_params("LatticeWithGram", "n::RngIntElt, Q::SeqEnum -> Lat", &cp, doc, lattice_with_gram);
    it.def("StandardLattice", "n::RngIntElt -> Lat", "The standard lattice Z^n.", standard_lattice);
    it.def("CoordinateLattice", "L::Lat -> Lat", "The lattice with the standard basis and the Gram matrix of L.", coordinate_lattice_of);
    for name in ["Module", "ZLattice"] {
        it.def(name, "L::Lat -> Lat", "The lattice L.", itself);
    }
    let doc = "The coordinate lattice of L with its Gram matrix scaled by s.";
    it.def("ScaledLattice", "L::Lat, s::RngIntElt -> Lat", doc, scaled_lattice);
    it.def("ScaledLattice", "L::Lat, s::FldRatElt -> Lat", doc, scaled_lattice);
}

