[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
repository = "https://github.com/aygerix/calyx-math"
rust-version = "1.85"

[workspace.dependencies]
calyx-flint = { path = "crates/calyx-flint" }
calyx-groebner = { path = "crates/calyx-groebner" }
calyx-syntax = { path = "crates/calyx-syntax" }
calyx-runtime = { path = "crates/calyx-runtime" }
flint3-sys = { version = "3.6.1" }
libc = "0.2"
indexmap = "2"
regex = "1"
rustc-hash = "2"
smallvec = { version = "1.13", features = ["union"] }
rustyline = "18"
ctrlc = "3.5"
mimalloc = { version = "0.1.52", default-features = false }

[profile.release]
debug = 1
lto = "thin"

[profile.dev.package."*"]
opt-level = 2
